version: "3.8"
services:
  web:
    image: lucleonard/sound-visualizer-web:latest
    ports:
      - "5000:80"
    env_file:
      - ../for_docker/config.env
    environment:
      - PYTHON_UNBUFFERED=1
    volumes:
    - "../for_docker/sound-visualizer-credentials.json:/sound-visualizer-credentials.json"

  worker:
    image: lucleonard/sound-visualizer-worker:latest
    env_file:
      - ../for_docker/config.env
    environment:
      - PYTHON_UNBUFFERED=1
    volumes:
        - "../for_docker/sound-visualizer-credentials.json:/sound-visualizer-credentials.json"