
version: "3.8"
services:
  web:
    image: lucleonard/sound-visualizer-api:latest
    ports:
      - "5001:80"
    env_file:
      - ../for_docker/config.env
    environment:
      - PYTHON_UNBUFFERED=1
      - APP_CORS_ORIGIN=http://localhost:8080
    volumes:
    - "../for_docker/sound-visualizer-credentials.json:/sound-visualizer-credentials.json"

  downloader:
    image: lucleonard/sound-visualizer-downloader:latest
    env_file:
      - ../for_docker/config.env
    environment:
      - PYTHON_UNBUFFERED=1
    volumes:
        - "../for_docker/sound-visualizer-credentials.json:/sound-visualizer-credentials.json"
