FROM python:3.9-slim as builder
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        # deps for installing poetry
        curl \
        # deps for building python deps
        build-essential

ENV PYTHONUNBUFFERED=1 \
    # prevents python creating .pyc files
    PYTHONDONTWRITEBYTECODE=1 \
    \
    # pip
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    \
    # poetry
    # https://python-poetry.org/docs/configuration/#using-environment-variables
    POETRY_VERSION=1.1.3 \
    # make poetry install to this location
    POETRY_HOME="/opt/poetry" \
    # make poetry create the virtual environment in the project's root
    # it gets named `.venv`
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    # do not ask any interactive question
    POETRY_NO_INTERACTION=1 \
    \
    # paths
    # this is where our requirements + virtual environment will live
    PYSETUP_PATH="/opt/pysetup" \
    VENV_PATH="/opt/pysetup/.venv"

ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
WORKDIR $PYSETUP_PATH
COPY ./poetry.lock pyproject.toml ./
RUN poetry update install --no-dev

FROM python:3.9-slim as prod
COPY --from=builder "/opt/pysetup" "/opt/pysetup"
COPY vendor/ffmpeg /bin/ffmpeg
COPY ./sound_visualizer/ /app/sound_visualizer
COPY ./logging_conf.json /app/logging_conf.json

WORKDIR /app/
ENV _IN_DOCKER=1
ENV VENV_PATH="/opt/pysetup/.venv"
ENV PYTHONPATH="$PYTHONPATH:."
ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"

ARG WORKER_MAIN="sound_visualizer/worker/main_worker.py"
RUN echo "main = " $WORKER_MAIN
ENV WORKER_MAIN ${WORKER_MAIN}
CMD python ${WORKER_MAIN}
