def boolean hasChangesIn(String module) {
  return !env.CHANGE_TARGET || sh(
    returnStatus: true,
    script: "git diff --name-only origin/${env.CHANGE_TARGET} ${env.GIT_COMMIT} | grep ^${module}/"
  ) == 0
}


pipeline {
	agent {
	  docker {
	  	image 'node:10'
	    args '''-v $HOME/.pip:/pip-cache
	    		-e _IN_DOCKER=1
	          -v /var/run/docker.sock:/var/run/docker.sock
	          -v /usr/bin/docker:/usr/bin/docker
	          --network sound-visualizer-testing-network
	          '''
	   }
	}
	stages {
		stage('ALL') {
			when {
	 			anyOf {
	 				 expression {
   						 return hasChangesIn('static')
  					}
					branch 'main'
	 			}
	 		}

			stages {
				stage('install deps') {
					steps {
						dir('static') {
							sh 'yarn install'
						}
				  	}
				}
				stage('Lint') {
					steps {
						sh 'echo lint'
					}
				}
				stage ('test') {
					steps {
						sh 'echo test'
					}
				}
				stage('build') {
						steps {
							dir('static') {
								sh 'yarn build'
							}
						}
				}
			}
		}
	}
}