pipeline {
	agent {
	  docker {
	  	image 'python:3.9-buster'
	    args '''-v $HOME/.pip:/pip-cache
	    		-e _IN_DOCKER=1
	          -v /var/run/docker.sock:/var/run/docker.sock
	          -v /usr/bin/docker:/usr/bin/docker
	          --network sound-visualizer-testing-network
	          '''
	   }
	}



    stages {
    stage('ALL') {
    	when { changeset "static/*"}
		stage('install deps') {
		  steps {

		  }
		}
		stage('Lint') {
				steps {

				}
			}
		stage ('test') {
			steps {

			}
		}
		stage('build docker image') {
				steps {
					sh 'yarn install'
				}
		}
   }
  }
}