pipeline {
	agent {
	  docker {
	  	image 'node:10'
	    args '''-v $HOME/.pip:/pip-cache
	    		-e _IN_DOCKER=1
	          -v /var/run/docker.sock:/var/run/docker.sock
	          -v /usr/bin/docker:/usr/bin/docker
	          --network sound-visualizer-testing-network
	          '''
	   }
	}
	stages {
		stage('ALL') {
			when { changeset "static/*"}

			stages {
				stage('install deps') {
					steps {
						sh 'yarn install'
				  	}
				}
				stage('Lint') {
					steps {
						sh 'echo lint'
					}
				}
				stage ('test') {
					steps {
						sh 'echo test'
					}
				}
				stage('build docker image') {
						steps {
							sh 'yarn build'
						}
				}
			}
		}
	}
}